---
title: "Fostering an Inclusive Culture: Call for Participation"
subtitle: ""
author: "Marco Gorelli, May Ireland, Melissa Mendonça, Inessa Pawson, Noa Tamir, Pamphile Roy"
date: "04/25/2023"
---

Have you often wondered how decisions get made across scientific open source
projects? Communications sometimes a little ‘off’? Think we can do better? Then
now’s the time to get involved.

Most folks who have been involved with open-source communities have thoughts and
ideas about what we can do to be more inclusive and welcoming. However, rarely
do we get a chance to have these conversations and express our points of view in
a constructive, collaborative way. 

As part of our
[CZI grant to Advance an Inclusive Culture in the scientific Python ecosystem](https://figshare.com/articles/online_resource/Advancing_an_inclusive_culture_in_the_scientific_Python_ecosystem/16548063),
we (maintainers and contributors to NumPy, SciPy, Matplotlib and pandas) have
been working in collaboration with [May Ireland](https://linkedin.com/in/mayireland)
to create a report with areas that are top of mind when we talk about improving
our projects’ cultures and being more inclusive. We want to be more intentional
about attracting, supporting and retaining people from diverse backgrounds to
join as contributors.

As a result of this report, we should like to focus on how we communicate with
each other, resolve disputes and make more informed decisions. We’ll soon be
kicking off a series of DEI Culture Labs to work on these three areas, and we
would like to invite participation from members of our communities, whether
already engaged with the projects or not. We would love to hear your ideas and
understand what we can do differently.

[Read the DEI Insights Report](https://drive.google.com/file/d/1pxSte5_M8-dZftFTPDxfaBwubJlDoCEb/view?usp=share_link)
and find out how you can help! You can also
[sign up here](https://contributor-experience.zulipchat.com/join/gogbsiflohlmfvwznmil6cjt/)
to the Contributor Experience Zulip chat, which is the communication channel we
will be using for these conversations.
